server:
  port: 8081

spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:mem:products
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
