<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/UserDataServiceApplication/GetDataFromCorpDB/CustomSQL" name="CustomSQL-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CustomSQL.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/UserDataServiceApplication/GetDataFromCorpDB/CustomSQL"/>
    <wsdl:binding name="CustomSQL_ptt-binding" type="cus:CustomSQL_ptt" xmlns:cus="http://xmlns.oracle.com/pcbpel/adapter/db/UserDataServiceApplication/GetDataFromCorpDB/CustomSQL">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CustomSQL">
            <soap:operation soapAction="CustomSQL"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>